apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMap }}
data:
  # kv format
  TZ: 'UTC+01:00'
  PORT: '80'
  HOST: '0.0.0.0'
  LOG_LEVEL: 'info'
  SESSION_DRIVER: 'cookie'
  NODE_ENV: 'production'
  FRONTEND_URL: '{{ .Values.frontendUrl }}'
  APP_VERSION: '{{ .Chart.AppVersion }}'
  ENVIRONMENT: '{{ .Values.environment }}'
  {{- if .Values.observability.tempo.enabled }}
  OTLP_ENDPOINT: '{{ .Values.observability.tempo.otlp_endpoint }}'
  {{- end }}
  {{- if .Values.observability.loki.enabled }}
  LOKI_HOST: '{{ .Values.observability.loki.address }}'
  {{- if ne .Values.observability.loki.logLevel "" }}
  LOKI_LOG_LEVEL: '{{ .Values.observability.loki.logLevel }}'
  {{- end }}
  {{- end }}
