---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: beep-production
spec:
  encryptedData:
    APP_KEY: AgA8kYQ2KkJQH7qnVuC+Udzx2C86l6kjJ1h9Mtwp1Lejm2FlmE8lFJPgFUMoK2ywPhg0iavzXjalg8BFZDKIiU0XHjYuaBG2Gf+qeKZ0nh5wZ9L+P2OjYIXFH3z0Z+xLYOUiCd5LqFWs++SUO8PKQrS4axbmYgv+GkrBwpyS5UGjHpq9CXpaTqHRCq+ZBbhaMuk3H8pXKJHVw0bj+GVmgXxyXZD0HOg+d5o2LCHk0uIuUxP8xC7wpDolKc4A2QiERw2vKDi2K6DyjOMYqoMXWY0/z/GiJhYYHS9FSXLuzVuHbRbovZr2RB+G60OwRg+aaKQkN7i8CO5mrc7bRsbeykZRRGeBSuxajf1/CuCOWljJl2lZEkrCTUeQAO2kM4rIV9ySQC4iAquKIxw8CNn3+eYI8F6ouHz3ZUqm17YevSBQIqgKdrzHwXSxwdcGOsrbplUrILkuuN6dbOEY+tI0OLhm+rOtmZeuZqNTsyvAVWMy9nCDve5l6opDHNijIM5y8kjwOj9q3cRBCWJ44dz+kj+x+vY2WX1w+BWt4HgJdi1bXjqMMdFryXxwz4Rb+TvfFM95etXR97/9Gj4MGKKdFlAzjRZRgGWp14Yb5/qXR9PyBF0HrEP8B671AEBOtsZm0OeysHHTVL0kxojYLtXDKMccgvF0nwss8+F5SjwpO2ktjQB3EoW7JBwDWYevBGnJtqnKRmw/+oDRBpZpuM/UkGdNStrjJpzNTm+c0lfAsl/6gJmlc5O24YTwzt0a/eHbMk5QLN+NBLv2a0h3Rgdrb0NB9+51AeedGyAAC8Waq+y0F1xP3S6co0DYFh6c1OudXbIhtLqv9CnxMcDzcw7ddEg7ByNCx1OVP8WX2oExOa8Wa3iweLbgOMYjbpw3RO9TasdoqUePklPBha1Cvgp7/97DdxExSKBvtiLX+Rl96Z3AUKjIuakeLDRMSO/GJekUvrGiCPjxQjHbekqzTsCa1em+me/Xp95x71hYGCqAeT6Nm5Ihdnu8UOsLkXgU9YdX3RnYoEttSuRsvcShYr+jcvD9bwF7v2EmzW/EYO1kSytdn8obDTzhkCgZ762k7BxHnB4UxxIbpOPULsbTmEZafFmBUAqu4IN90s8fJ8cBlyh2/qB0dfAyKylN5vsH0Qa4wi8rbWFljV9L7xp6jNEOD0i3XN9P27adtNtCfoZKfaIL+3b5OzZ6/4raw5zwT+GAWVTwLYCGpP7qCj4wOXWCYTLvUdc=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: beep-production
