image:
  pullPolicy: Always
  port: 80
  repository: registry.beep.ovh/beep/api
  tag: ""

environment: "prod"

observability:
  tempo:
    enabled: false
    otlp_endpoint: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
  loki:
    enabled: false
    address: "http://loki.monitoring.svc.cluster.local:3100"
    logLevel: ""

service:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: ""
      paths: ["/"]
  tls: []

replicaCount: 1

# Values below should be the same for all environments or they can be
# provided by the infrastructure
# Unless you know what you are doing, you should not change these values
imagePullSecrets:
  - name: harbor-registry

smtp:
  existingSecret: smtp-secret
  hostKey: host
  portKey: port
  userKey: user
  passwordKey: password

minio:
  existingSecret: minio-secret
  userKey: minio-user
  passwordKey: minio-password

postgresql:
  existingSecret: postgresql-secret
  passwordKey: postgres-password

redis:
  existingSecret: redis-secret
  passwordKey: redis-password

configService: beep-services-config

app:
  existingSecret: app-secret
  configMap: backend-config

frontendUrl: ""

secret:
  appKey: ""

  smtp:
    host: ""
    port: ""
    username: ""
    password: ""
