image:
  pullPolicy: Always
  port: 80
  repository: milou666/beep-api
  tag: ""

environment: "prod"

observability:
  enabled: false
  otlp_endpoint: ''

service:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: ""
      paths: ['/']


replicaCount: 1

# Values below should be the same for all environments or they can be
# provided by the infrastructure
# Unless you know what you are doing, you should not change these values
smtp:
  existingSecret: smtp-secret
  hostKey: host
  portKey: port
  userKey: user
  passwordKey: password

minio:
  existingSecret: minio-secret
  userKey: minio-user
  passwordKey: minio-password

postgresql:
  existingSecret: postgresql-secret
  passwordKey: postgres-password

redis:
  existingSecret: redis-secret
  passwordKey: redis-password

configService: beep-services-config

app:
  existingSecret: app-secret
  configMap: backend-config


frontendUrl: ""

secret:
  appKey: ""

  smtp:
    host: ""
    port: ""
    username: ""
    password: ""
