image:
  tag: "ba990b97-development"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: 'development.beep.ovh'
      paths:
        - /
  tls:
    - hosts:
        - "development.beep.ovh"
      secretName: front-development-beep-tls
