image:
  tag: "175601c9-development"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "development.beep.ovh"
      paths:
        - /
  tls:
    - hosts:
        - "development.beep.ovh"
      secretName: front-development-beep-tls
