image:
  tag: "1.6.0"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "beep.ovh"
      paths:
        - /
  tls:
    - hosts:
        - "beep.ovh"
      secretName: front-beep-tls
