image:
  tag: "6f3ccb02-staging"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "staging.beep.ovh"
      paths:
        - /
  tls:
    - hosts:
        - "staging.beep.ovh"
      secretName: front-staging-beep-tls
