replicaCount: 1
imagePullSecrets:
  - name: beep-registry
resources: {}
service:
  type: ClusterIP
  port: 80
image:
  pullPolicy: Always
  port: 8080
  repository: 'milou666/beep-front'
  tag: ""

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: 'staging.beep.ovh'
      paths:
        - /
  tls: []
