apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webrtclixir.fullname" . }}
  labels:
    {{- include "webrtclixir.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "webrtclixir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webrtclixir.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: "80"
          - name: SECRET_KEY_BASE
            value: {{ .Values.env.secretKey }}
          - name: PHX_HOST
            value: {{ .Values.env.phxHost }}
          - name: ADMIN_USERNAME
            value: {{ .Values.env.adminUsername }}
          - name: ADMIN_PASSWORD
            value: {{ .Values.env.adminPassword }}
          - name: ICE_PORT_RANGE
            value: {{ .Values.env.icePortRange }}
          - name: PHX_SERVER
            value: "1"
          - name: NEXUS_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}