image:
  tag: "3a8be3ed-development"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "voice-development.beep.ovh"
      paths:
        - /
  tls:
    - hosts:
        - "voice-development.beep.ovh"
      secretName: voice-development-beep-tls
env:
  phxHost: "voice-development.beep.ovh"
